SELECT ECE.ECO_RECIBO, * FROM FPG_REGISTROS_ESOCIAL_S_1200 FE
	INNER JOIN ESOCIAL_CONTROLA_ENVIO ECE
	ON FE.PES_COD = ECE.ECO_CHAVE AND ECE.ETA_COD = 'S-1200' 

WHERE FE.cpfTrab = '93647018520' AND FE.perApur = '2022-07'
--------------------------------------------------------------
UPDATE ESOCIAL_CONTROLA_ENVIO 
SET ECO_RECIBO = NULL
FROM FPG_REGISTROS_ESOCIAL_S_1200 FE
INNER JOIN ESOCIAL_CONTROLA_ENVIO ECE
ON FE.PES_COD = ECE.ECO_CHAVE AND ECE.ETA_COD = 'S-1200'
WHERE FE.cpfTrab = '93647018520' AND FE.perApur = '2022-07'