SELECT S2.ID, S2.nmTrab,  ECE.ECO_RECIBO, S2.matricula, ECE.ECO_CHAVE, S2.nrRecibo


FROM FPG_REGISTROS_ESOCIAL_S_2200 S2 INNER JOIN ESOCIAL_CONTROLA_ENVIO ECE 
ON S2.CHAVE = ECE.ECO_CHAVE AND ECE.ETA_COD = 'S-2200'

WHERE S2.matricula = 162


/*UPDATE ESOCIAL_CONTROLA_ENVIO 
SET ECO_RECIBO = ''
FROM ESOCIAL_CONTROLA_ENVIO ECE INNER JOIN FPG_REGISTROS_ESOCIAL_S_2200 S2 
ON S2.CHAVE = ECE.ECO_CHAVE AND ECE.ETA_COD = 'S-2200'

WHERE S2.matricula = 162*/


