SELECT ECE.ECO_RECIBO, ECE.ECO_CHAVE


FROM GER_FUNCIONARIO GF INNER JOIN ESOCIAL_CONTROLA_ENVIO ECE 
ON GF.FUN_MATRICULA = ECE.ECO_CHAVE AND ECE.ETA_COD = 'S-2200'

WHERE GF.FUN_MATRICULA = 162


UPDATE ESOCIAL_CONTROLA_ENVIO 
SET ECO_RECIBO = NULL
FROM ESOCIAL_CONTROLA_ENVIO ECE INNER JOIN GER_FUNCIONARIO GF
ON GF.FUN_MATRICULA = ECE.ECO_CHAVE AND ECE.ETA_COD = 'S-2200'

WHERE GF.FUN_MATRICULA = 162


