USE FPG_WEB_PM_ITAPETINGA

SELECT S2.ID,   ECE.ECO_RECIBO, S2.matricula, ECE.ECO_CHAVE


FROM FPG_REGISTROS_ESOCIAL_S_2299 S2 INNER JOIN ESOCIAL_CONTROLA_ENVIO ECE 
ON S2.CHAVE = ECE.ECO_CHAVE AND ECE.ETA_COD = 'S-2299'

WHERE S2.matricula = 16300

UPDATE ESOCIAL_CONTROLA_ENVIO 
SET ECO_RECIBO = NULL
FROM ESOCIAL_CONTROLA_ENVIO ECE INNER JOIN FPG_REGISTROS_ESOCIAL_S_2299  S2 
ON S2.CHAVE = ECE.ECO_CHAVE AND ECE.ETA_COD = 'S-2299'

WHERE S2.matricula = 16300


